const {
  Document, Packer, Paragraph, TextRun, Table, TableRow, TableCell,
  HeadingLevel, AlignmentType, BorderStyle, WidthType, ShadingType,
  LevelFormat, PageNumber, PageBreak, Header, Footer, TabStopType,
  TabStopPosition, ExternalHyperlink
} = require('docx');
const fs = require('fs');

// ─── COLORS ───────────────────────────────────────────────
const C = {
  primary:   "1A3A5C",
  accent:    "E8C547",
  green:     "2D7D46",
  red:       "C0392B",
  blue:      "2471A3",
  gray1:     "2C3E50",
  gray2:     "566573",
  gray3:     "AAB7B8",
  grayBg:    "F2F3F4",
  headerBg:  "1A3A5C",
  codeBg:    "F8F9FA",
  tableHead: "1A3A5C",
  tableAlt:  "EBF5FB",
  border:    "BFC9CA",
  accentBg:  "FEF9E7",
  greenBg:   "EAFAF1",
  redBg:     "FDEDEC",
  white:     "FFFFFF",
};

// ─── HELPERS ──────────────────────────────────────────────
const bdr = (color = C.border) => ({
  top:    { style: BorderStyle.SINGLE, size: 1, color },
  bottom: { style: BorderStyle.SINGLE, size: 1, color },
  left:   { style: BorderStyle.SINGLE, size: 1, color },
  right:  { style: BorderStyle.SINGLE, size: 1, color },
});

const noBdr = () => ({
  top:    { style: BorderStyle.NONE, size: 0, color: "FFFFFF" },
  bottom: { style: BorderStyle.NONE, size: 0, color: "FFFFFF" },
  left:   { style: BorderStyle.NONE, size: 0, color: "FFFFFF" },
  right:  { style: BorderStyle.NONE, size: 0, color: "FFFFFF" },
});

const cell = (children, opts = {}) => new TableCell({
  borders: opts.borders ?? bdr(),
  width: opts.width ?? { size: opts.w ?? 4680, type: WidthType.DXA },
  shading: opts.shading ?? { fill: opts.fill ?? C.white, type: ShadingType.CLEAR },
  margins: opts.margins ?? { top: 100, bottom: 100, left: 150, right: 150 },
  verticalAlign: opts.va,
  children,
});

const p = (text, opts = {}) => new Paragraph({
  heading: opts.heading,
  alignment: opts.align ?? AlignmentType.LEFT,
  spacing: opts.spacing ?? { before: opts.before ?? 0, after: opts.after ?? 80 },
  indent: opts.indent,
  numbering: opts.numbering,
  border: opts.border,
  children: typeof text === 'string'
    ? [new TextRun({ text, font: opts.font ?? "Arial", size: opts.size ?? 20,
        bold: opts.bold, italic: opts.italic, color: opts.color,
        break: opts.break })]
    : text,
});

const t = (text, opts = {}) => new TextRun({
  text, font: opts.font ?? "Arial", size: opts.size ?? 20,
  bold: opts.bold, italic: opts.italic, color: opts.color ?? C.gray1,
  highlight: opts.highlight, break: opts.break,
});

const codeRun = (text) => new TextRun({
  text, font: "Courier New", size: 18, color: C.primary,
});

const codePara = (text, opts = {}) => new Paragraph({
  spacing: { before: 0, after: 0 },
  indent: { left: 0 },
  children: [new TextRun({ text, font: "Courier New", size: 17, color: "2471A3" })],
});

const h1 = (text) => new Paragraph({
  heading: HeadingLevel.HEADING_1,
  spacing: { before: 320, after: 160 },
  border: { bottom: { style: BorderStyle.SINGLE, size: 6, color: C.accent } },
  children: [new TextRun({ text, font: "Arial", size: 36, bold: true, color: C.primary })],
});

const h2 = (text) => new Paragraph({
  heading: HeadingLevel.HEADING_2,
  spacing: { before: 240, after: 120 },
  children: [new TextRun({ text, font: "Arial", size: 28, bold: true, color: C.primary })],
});

const h3 = (text) => new Paragraph({
  heading: HeadingLevel.HEADING_3,
  spacing: { before: 160, after: 80 },
  children: [new TextRun({ text, font: "Arial", size: 24, bold: true, color: C.blue })],
});

const bullet = (text, level = 0) => new Paragraph({
  numbering: { reference: "bullets", level },
  spacing: { before: 40, after: 40 },
  children: [new TextRun({ text, font: "Arial", size: 20, color: C.gray1 })],
});

const numbered = (text, level = 0) => new Paragraph({
  numbering: { reference: "numbers", level },
  spacing: { before: 40, after: 40 },
  children: [new TextRun({ text, font: "Arial", size: 20, color: C.gray1 })],
});

const space = (n = 1) => Array(n).fill(p("", { after: 0, before: 0 }));

// Colored info box
const infoBox = (label, text, fillColor, labelColor) => new Table({
  width: { size: 9360, type: WidthType.DXA },
  columnWidths: [1400, 7960],
  rows: [new TableRow({ children: [
    cell([p([t(label, { bold: true, color: labelColor ?? C.white, size: 19 })],
      { after: 0 })], { w: 1400, fill: labelColor ? fillColor : C.primary,
      borders: noBdr(), margins: { top: 100, bottom: 100, left: 140, right: 140 } }),
    cell([p(text, { after: 0, size: 19, color: C.gray1 })],
      { w: 7960, fill: fillColor, borders: noBdr(),
        margins: { top: 100, bottom: 100, left: 140, right: 140 } }),
  ]})],
});

// Code block table
const codeBlock = (lines) => new Table({
  width: { size: 9360, type: WidthType.DXA },
  columnWidths: [9360],
  rows: [new TableRow({ children: [
    cell(
      lines.map(l => new Paragraph({
        spacing: { before: 0, after: 0 },
        children: [new TextRun({ text: l, font: "Courier New", size: 17, color: "2471A3" })],
      })),
      { w: 9360, fill: C.codeBg,
        borders: { top: bdr(C.border).top, bottom: bdr(C.border).bottom,
                   left: { style: BorderStyle.SINGLE, size: 12, color: C.accent },
                   right: bdr(C.border).right },
        margins: { top: 120, bottom: 120, left: 160, right: 160 } }
    )
  ]})],
});

// Section divider
const divider = () => new Paragraph({
  spacing: { before: 40, after: 40 },
  border: { bottom: { style: BorderStyle.SINGLE, size: 2, color: C.gray3 } },
  children: [],
});

// ─── COVER PAGE ───────────────────────────────────────────
const coverPage = [
  ...space(4),
  new Paragraph({
    alignment: AlignmentType.CENTER,
    spacing: { before: 0, after: 80 },
    children: [new TextRun({ text: "SPÉCIFICATIONS TECHNIQUES DU PROJET", font: "Arial", size: 24, color: C.gray2, bold: true })],
  }),
  new Paragraph({
    alignment: AlignmentType.CENTER,
    spacing: { before: 0, after: 200 },
    children: [new TextRun({ text: "Machine Learning — Finance & Banque", font: "Arial", size: 22, color: C.gray3 })],
  }),
  new Paragraph({
    alignment: AlignmentType.CENTER,
    spacing: { before: 0, after: 80 },
    border: {
      top: { style: BorderStyle.SINGLE, size: 12, color: C.accent },
      bottom: { style: BorderStyle.SINGLE, size: 12, color: C.accent },
    },
    children: [
      new TextRun({ text: " ", font: "Arial", size: 8 }),
      new TextRun({ break: 1 }),
      new TextRun({ text: "Détection de Fraude Bancaire", font: "Arial", size: 52, bold: true, color: C.primary }),
      new TextRun({ break: 1 }),
      new TextRun({ text: "en Temps Réel", font: "Arial", size: 52, bold: true, color: C.accent }),
      new TextRun({ break: 1 }),
      new TextRun({ text: " ", font: "Arial", size: 8 }),
    ],
  }),
  ...space(1),
  new Paragraph({
    alignment: AlignmentType.CENTER,
    spacing: { before: 80, after: 40 },
    children: [new TextRun({ text: "Projet End-to-End · Niveau Intermédiaire → Avancé", font: "Arial", size: 22, italic: true, color: C.gray2 })],
  }),
  ...space(3),
  new Table({
    width: { size: 6000, type: WidthType.DXA },
    columnWidths: [3000, 3000],
    rows: [
      new TableRow({ children: [
        cell([p([t("Version", { bold: true, size: 19, color: C.gray2 })])], { w: 3000, fill: C.grayBg, borders: noBdr() }),
        cell([p([t("1.0.0", { size: 19, color: C.gray1 })])], { w: 3000, fill: C.grayBg, borders: noBdr() }),
      ]}),
      new TableRow({ children: [
        cell([p([t("Durée estimée", { bold: true, size: 19, color: C.gray2 })])], { w: 3000, fill: C.white, borders: noBdr() }),
        cell([p([t("6 à 8 semaines", { size: 19, color: C.gray1 })])], { w: 3000, fill: C.white, borders: noBdr() }),
      ]}),
      new TableRow({ children: [
        cell([p([t("Domaine", { bold: true, size: 19, color: C.gray2 })])], { w: 3000, fill: C.grayBg, borders: noBdr() }),
        cell([p([t("Finance · Banque · Fintech", { size: 19, color: C.gray1 })])], { w: 3000, fill: C.grayBg, borders: noBdr() }),
      ]}),
      new TableRow({ children: [
        cell([p([t("Auteur", { bold: true, size: 19, color: C.gray2 })])], { w: 3000, fill: C.white, borders: noBdr() }),
        cell([p([t("Étudiant en Data Science & IA", { size: 19, color: C.gray1 })])], { w: 3000, fill: C.white, borders: noBdr() }),
      ]}),
    ],
  }),
  new Paragraph({ children: [new PageBreak()] }),
];

// ─── TABLE OF CONTENTS (manual) ────────────────────────────
const tocPage = [
  h1("Table des matières"),
  ...space(1),
  ...([
    ["1.", "Vue d'ensemble du projet", "3"],
    ["2.", "Architecture & Structure des dossiers", "5"],
    ["3.", "Environnement & Dépendances", "7"],
    ["4.", "Données & Feature Engineering", "9"],
    ["5.", "Pipeline de Modélisation", "13"],
    ["6.", "Explicabilité & Visualisation", "17"],
    ["7.", "API & Déploiement", "19"],
    ["8.", "MLflow & Suivi des expériences", "22"],
    ["9.", "Tests & Qualité du code", "24"],
    ["10.", "Livrables & Critères de succès", "26"],
  ].map(([num, title, page]) => new Paragraph({
    spacing: { before: 60, after: 60 },
    tabStops: [{ type: TabStopType.RIGHT, position: TabStopPosition.MAX, leader: "dot" }],
    children: [
      new TextRun({ text: `${num}  ${title}`, font: "Arial", size: 20, color: C.gray1 }),
      new TextRun({ text: "\t", font: "Arial", size: 20 }),
      new TextRun({ text: page, font: "Arial", size: 20, color: C.gray2 }),
    ],
  }))),
  new Paragraph({ children: [new PageBreak()] }),
];

// ─── SECTION 1 : VUE D'ENSEMBLE ───────────────────────────
const section1 = [
  h1("1. Vue d'ensemble du projet"),
  h2("1.1 Contexte & Objectif"),
  p("La fraude bancaire représente des milliards d'euros de pertes annuelles pour les institutions financières mondiales. Ce projet consiste à construire un système de détection de fraude end-to-end : de l'ingestion des données brutes jusqu'au déploiement d'une API de prédiction en temps réel, avec explicabilité et monitoring."),
  ...space(1),
  p("L'objectif principal n'est pas uniquement de construire un modèle performant, mais de produire un système complet, documenté et déployé, tel qu'il pourrait exister en production dans une banque ou une fintech."),
  ...space(1),
  h2("1.2 Problème technique central"),
  infoBox("⚠  DÉFI", "Le dataset contient ~0.17% de fraudes seulement. Avec un tel déséquilibre, un modèle qui prédit 'jamais fraude' atteint déjà 99.83% d'accuracy — ce qui est totalement inutile. La gestion de ce déséquilibre est le vrai enjeu technique.", C.accentBg),
  ...space(1),
  p("Les trois défis techniques majeurs à résoudre :"),
  bullet("Déséquilibre de classes extrême (ratio 1:578 entre fraudes et transactions légitimes)"),
  bullet("Choix des bonnes métriques d'évaluation (PR-AUC, F1 sur classe minoritaire, coût métier)"),
  bullet("Feature engineering temporel et contextuel pour capturer les patterns de fraude"),
  bullet("Explicabilité des décisions pour répondre aux exigences réglementaires bancaires (RGPD, DSP2)"),
  ...space(1),
  h2("1.3 Périmètre du projet"),
  new Table({
    width: { size: 9360, type: WidthType.DXA },
    columnWidths: [3120, 6240],
    rows: [
      new TableRow({ children: [
        cell([p([t("Composante", { bold: true, color: C.white, size: 19 })])], { w: 3120, fill: C.tableHead, margins: { top: 100, bottom: 100, left: 150, right: 150 } }),
        cell([p([t("Description", { bold: true, color: C.white, size: 19 })])], { w: 6240, fill: C.tableHead, margins: { top: 100, bottom: 100, left: 150, right: 150 } }),
      ]}),
      ...[
        ["Data Pipeline", "Ingestion, nettoyage, feature engineering, validation des données"],
        ["Modélisation", "Entraînement, comparaison de modèles, tuning des hyperparamètres"],
        ["Explicabilité", "Analyse SHAP globale et locale, visualisations interactives"],
        ["API REST", "Endpoint FastAPI pour prédiction temps réel (latence < 50ms)"],
        ["Interface", "Dashboard Streamlit pour démonstration et monitoring"],
        ["MLOps", "Tracking MLflow, versioning DVC, Docker, déploiement cloud"],
        ["Tests", "Tests unitaires, tests d'intégration, tests de non-régression"],
      ].map(([comp, desc], i) => new TableRow({ children: [
        cell([p([t(comp, { bold: true, size: 19, color: C.primary })])],
          { w: 3120, fill: i % 2 === 0 ? C.grayBg : C.white }),
        cell([p([t(desc, { size: 19, color: C.gray1 })])],
          { w: 6240, fill: i % 2 === 0 ? C.grayBg : C.white }),
      ]})),
    ],
  }),
  ...space(1),
  h2("1.4 Stack technique"),
  new Table({
    width: { size: 9360, type: WidthType.DXA },
    columnWidths: [2340, 3510, 3510],
    rows: [
      new TableRow({ children: [
        cell([p([t("Catégorie", { bold: true, color: C.white, size: 19 })])], { w: 2340, fill: C.tableHead }),
        cell([p([t("Outils principaux", { bold: true, color: C.white, size: 19 })])], { w: 3510, fill: C.tableHead }),
        cell([p([t("Justification", { bold: true, color: C.white, size: 19 })])], { w: 3510, fill: C.tableHead }),
      ]}),
      ...[
        ["Data", "pandas, numpy, scikit-learn", "Standards industrie, excellente documentation"],
        ["Modèles", "XGBoost, LightGBM, CatBoost", "SOTA sur données tabulaires, gestion déséquilibre"],
        ["Explicabilité", "SHAP, matplotlib, plotly", "Requis en finance (interprétabilité réglementaire)"],
        ["API", "FastAPI, Pydantic, uvicorn", "Performant, typage fort, documentation auto (OpenAPI)"],
        ["MLOps", "MLflow, DVC, Docker", "Tracking complet, reproductibilité, déploiement"],
        ["Tests", "pytest, pytest-cov", "Couverture de code, CI/CD ready"],
        ["Deploy", "Railway / Render, Streamlit Cloud", "Gratuit, démo publique accessible"],
      ].map(([cat, tools, just], i) => new TableRow({ children: [
        cell([p([t(cat, { bold: true, size: 19, color: C.primary })])],
          { w: 2340, fill: i % 2 === 0 ? C.grayBg : C.white }),
        cell([p([t(tools, { size: 19, color: C.gray1, font: "Courier New" })])],
          { w: 3510, fill: i % 2 === 0 ? C.grayBg : C.white }),
        cell([p([t(just, { size: 19, color: C.gray2 })])],
          { w: 3510, fill: i % 2 === 0 ? C.grayBg : C.white }),
      ]})),
    ],
  }),
  new Paragraph({ children: [new PageBreak()] }),
];

// ─── SECTION 2 : STRUCTURE DES DOSSIERS ──────────────────
const section2 = [
  h1("2. Architecture & Structure des dossiers"),
  h2("2.1 Arborescence complète du projet"),
  infoBox("💡 RÈGLE", "Chaque dossier a une responsabilité unique. Ne jamais mélanger code de production, notebooks d'exploration et scripts de déploiement dans le même dossier.", C.accentBg),
  ...space(1),
  codeBlock([
    "fraud-detection/",
    "│",
    "├── data/",
    "│   ├── raw/                    # Données brutes téléchargées (non versionnées - .gitignore)",
    "│   ├── processed/              # Données après nettoyage et feature engineering",
    "│   └── external/               # Données tierces (taux de change, calendriers...)",
    "│",
    "├── notebooks/",
    "│   ├── 01_eda.ipynb            # Exploration et analyse statistique",
    "│   ├── 02_features.ipynb       # Feature engineering détaillé",
    "│   ├── 03_modeling.ipynb       # Comparaison et sélection de modèles",
    "│   ├── 04_explainability.ipynb # Analyse SHAP et visualisations",
    "│   └── 05_monitoring.ipynb     # Simulation drift et monitoring",
    "│",
    "├── src/                        # Code source de production",
    "│   ├── __init__.py",
    "│   ├── config.py               # Constantes, chemins, paramètres globaux",
    "│   ├── data/",
    "│   │   ├── __init__.py",
    "│   │   ├── loader.py           # Chargement et validation des données brutes",
    "│   │   └── preprocessor.py     # Nettoyage et préparation",
    "│   ├── features/",
    "│   │   ├── __init__.py",
    "│   │   ├── temporal.py         # Features temporelles (heure, vélocité...)",
    "│   │   ├── statistical.py      # Features statistiques (z-score, ratios...)",
    "│   │   └── pipeline.py         # Pipeline sklearn complet",
    "│   ├── models/",
    "│   │   ├── __init__.py",
    "│   │   ├── train.py            # Script d'entraînement principal",
    "│   │   ├── evaluate.py         # Métriques personnalisées (PR-AUC, coût métier)",
    "│   │   └── predict.py          # Inference sur nouvelles données",
    "│   └── explainability/",
    "│       ├── __init__.py",
    "│       └── shap_utils.py       # Calcul et visualisation SHAP",
    "│",
    "├── api/",
    "│   ├── main.py                 # Application FastAPI",
    "│   ├── schemas.py              # Modèles Pydantic (validation des entrées)",
    "│   ├── dependencies.py         # Injection de dépendances (modèle, config)",
    "│   └── routers/",
    "│       ├── predict.py          # Route POST /predict",
    "│       └── health.py           # Route GET /health",
    "│",
    "├── dashboard/",
    "│   └── app.py                  # Interface Streamlit de démonstration",
    "│",
    "├── tests/",
    "│   ├── __init__.py",
    "│   ├── test_features.py        # Tests unitaires feature engineering",
    "│   ├── test_model.py           # Tests de performance du modèle",
    "│   ├── test_api.py             # Tests d'intégration de l'API",
    "│   └── fixtures/               # Données de test (petits échantillons)",
    "│",
    "├── mlruns/                     # Artefacts MLflow (auto-généré, gitignore)",
    "├── models/                     # Modèles sérialisés (.pkl, .joblib)",
    "│",
    "├── .github/workflows/",
    "│   └── ci.yml                  # Pipeline CI/CD GitHub Actions",
    "│",
    "├── Dockerfile",
    "├── docker-compose.yml",
    "├── requirements.txt",
    "├── requirements-dev.txt        # Dépendances de développement (pytest, black...)",
    "├── setup.py",
    "├── .env.example                # Variables d'environnement (template)",
    "├── .gitignore",
    "├── dvc.yaml                    # Pipeline DVC",
    "└── README.md                   # Documentation principale avec GIF de démo",
  ]),
  ...space(1),
  h2("2.2 Règles de nommage & conventions"),
  new Table({
    width: { size: 9360, type: WidthType.DXA },
    columnWidths: [2340, 3510, 3510],
    rows: [
      new TableRow({ children: [
        cell([p([t("Élément", { bold: true, color: C.white, size: 19 })])], { w: 2340, fill: C.tableHead }),
        cell([p([t("Convention", { bold: true, color: C.white, size: 19 })])], { w: 3510, fill: C.tableHead }),
        cell([p([t("Exemple", { bold: true, color: C.white, size: 19 })])], { w: 3510, fill: C.tableHead }),
      ]}),
      ...[
        ["Fichiers Python", "snake_case", "feature_engineering.py"],
        ["Classes", "PascalCase", "FraudDetector, DataLoader"],
        ["Fonctions/Variables", "snake_case", "compute_velocity(), fraud_score"],
        ["Constantes", "UPPER_SNAKE_CASE", "MODEL_PATH, FRAUD_THRESHOLD"],
        ["Branches Git", "feature/ ou fix/ ou chore/", "feature/shap-explainability"],
        ["Commits Git", "Conventional Commits", "feat: add SHAP force plot endpoint"],
      ].map(([el, conv, ex], i) => new TableRow({ children: [
        cell([p([t(el, { bold: true, size: 19, color: C.primary })])],
          { w: 2340, fill: i % 2 === 0 ? C.grayBg : C.white }),
        cell([p([t(conv, { size: 19, color: C.gray1 })])],
          { w: 3510, fill: i % 2 === 0 ? C.grayBg : C.white }),
        cell([p([t(ex, { size: 19, color: C.blue, font: "Courier New" })])],
          { w: 3510, fill: i % 2 === 0 ? C.grayBg : C.white }),
      ]})),
    ],
  }),
  new Paragraph({ children: [new PageBreak()] }),
];

// ─── SECTION 3 : ENVIRONNEMENT ───────────────────────────
const section3 = [
  h1("3. Environnement & Dépendances"),
  h2("3.1 Prérequis système"),
  bullet("Python 3.10 ou supérieur"),
  bullet("Git 2.30+"),
  bullet("Docker 24+ (pour le déploiement)"),
  bullet("8 Go RAM minimum (16 Go recommandé pour les grands datasets)"),
  bullet("Compte GitHub (CI/CD) + compte Railway ou Render (déploiement gratuit)"),
  ...space(1),
  h2("3.2 Installation de l'environnement"),
  p("Suivre ces étapes dans l'ordre exact. Ne jamais travailler sans environnement virtuel activé."),
  ...space(1),
  codeBlock([
    "# 1. Cloner le dépôt",
    "git clone https://github.com/votre-username/fraud-detection.git",
    "cd fraud-detection",
    "",
    "# 2. Créer l'environnement virtuel",
    "python -m venv venv",
    "",
    "# 3. Activer l'environnement (Linux/Mac)",
    "source venv/bin/activate",
    "# Sur Windows :",
    "# venv\\Scripts\\activate",
    "",
    "# 4. Installer les dépendances",
    "pip install -r requirements.txt",
    "pip install -r requirements-dev.txt",
    "",
    "# 5. Configurer les variables d'environnement",
    "cp .env.example .env",
    "# Éditer .env avec vos clés API",
  ]),
  ...space(1),
  h2("3.3 Fichier requirements.txt"),
  codeBlock([
    "# === Data Processing ===",
    "pandas==2.2.0",
    "numpy==1.26.4",
    "scipy==1.12.0",
    "",
    "# === Machine Learning ===",
    "scikit-learn==1.4.0",
    "xgboost==2.0.3",
    "lightgbm==4.3.0",
    "catboost==1.2.3",
    "imbalanced-learn==0.12.0",
    "optuna==3.5.0",
    "",
    "# === Explicabilité ===",
    "shap==0.44.1",
    "matplotlib==3.8.2",
    "seaborn==0.13.2",
    "plotly==5.18.0",
    "",
    "# === MLOps ===",
    "mlflow==2.10.0",
    "dvc==3.40.1",
    "joblib==1.3.2",
    "",
    "# === API ===",
    "fastapi==0.109.0",
    "uvicorn[standard]==0.27.0",
    "pydantic==2.6.0",
    "",
    "# === Dashboard ===",
    "streamlit==1.31.0",
  ]),
  ...space(1),
  h2("3.4 Variables d'environnement (.env)"),
  codeBlock([
    "# Chemins des données",
    "DATA_RAW_PATH=data/raw/creditcard.csv",
    "DATA_PROCESSED_PATH=data/processed/features.parquet",
    "MODEL_PATH=models/fraud_detector_v1.pkl",
    "",
    "# MLflow",
    "MLFLOW_TRACKING_URI=./mlruns",
    "MLFLOW_EXPERIMENT_NAME=fraud_detection",
    "",
    "# API",
    "API_HOST=0.0.0.0",
    "API_PORT=8000",
    "FRAUD_THRESHOLD=0.5       # Seuil de décision (ajustable)",
    "REVIEW_THRESHOLD=0.3      # Seuil pour mise en révision",
    "",
    "# Monitoring",
    "DRIFT_ALERT_THRESHOLD=0.1  # Seuil de dérive PSI",
  ]),
  new Paragraph({ children: [new PageBreak()] }),
];

// ─── SECTION 4 : DONNÉES ─────────────────────────────────
const section4 = [
  h1("4. Données & Feature Engineering"),
  h2("4.1 Datasets"),
  p("Trois datasets sont utilisés selon la phase du projet :"),
  ...space(1),
  new Table({
    width: { size: 9360, type: WidthType.DXA },
    columnWidths: [2600, 1800, 1560, 3400],
    rows: [
      new TableRow({ children: [
        cell([p([t("Dataset", { bold: true, color: C.white, size: 19 })])], { w: 2600, fill: C.tableHead }),
        cell([p([t("Taille", { bold: true, color: C.white, size: 19 })])], { w: 1800, fill: C.tableHead }),
        cell([p([t("Usage", { bold: true, color: C.white, size: 19 })])], { w: 1560, fill: C.tableHead }),
        cell([p([t("Source", { bold: true, color: C.white, size: 19 })])], { w: 3400, fill: C.tableHead }),
      ]}),
      ...[
        ["Credit Card Fraud (ULB)", "284 807 tx", "Principal", "kaggle.com/datasets/mlg-ulb/creditcardfraud"],
        ["IEEE-CIS Fraud Detection", "590 540 tx", "Avancé", "kaggle.com/competitions/ieee-fraud-detection"],
        ["PaySim Synthetic", "6.3 M tx", "Stress test", "kaggle.com/datasets/ealaxi/paysim1"],
      ].map(([name, size, usage, src], i) => new TableRow({ children: [
        cell([p([t(name, { bold: true, size: 19, color: C.primary })])],
          { w: 2600, fill: i % 2 === 0 ? C.grayBg : C.white }),
        cell([p([t(size, { size: 19, color: C.gray1 })])],
          { w: 1800, fill: i % 2 === 0 ? C.grayBg : C.white }),
        cell([p([t(usage, { size: 19, color: C.green, bold: true })])],
          { w: 1560, fill: i % 2 === 0 ? C.grayBg : C.white }),
        cell([p([t(src, { size: 17, color: C.blue, font: "Courier New" })])],
          { w: 3400, fill: i % 2 === 0 ? C.grayBg : C.white }),
      ]})),
    ],
  }),
  ...space(1),
  h2("4.2 Description du dataset principal (ULB)"),
  bullet("284 807 transactions réelles de cartes bancaires européennes (septembre 2013)"),
  bullet("28 features anonymisées V1 à V28 : résultats d'une transformation PCA pour confidentialité"),
  bullet("2 features non transformées : Time (secondes depuis la 1ère transaction) et Amount (montant en €)"),
  bullet("Variable cible : Class (0 = légitime, 1 = fraude) — 492 fraudes soit 0.172%"),
  ...space(1),
  infoBox("⚠  IMPORTANT", "Les features V1-V28 sont déjà des composantes PCA. Il n'est pas possible de créer des features basées sur leur signification métier réelle. Le feature engineering doit se concentrer sur Time, Amount et les patterns statistiques.", C.accentBg),
  ...space(1),
  h2("4.3 Feature Engineering — Implémentation complète"),
  h3("4.3.1 Features temporelles"),
  codeBlock([
    "# src/features/temporal.py",
    "",
    "import pandas as pd",
    "import numpy as np",
    "",
    "def add_temporal_features(df: pd.DataFrame) -> pd.DataFrame:",
    '    """Crée des features basées sur la colonne Time."""',
    "    df = df.copy()",
    "",
    "    # Heure de la journée (0-23)",
    "    df['hour_of_day'] = (df['Time'] % 86400) // 3600",
    "",
    "    # Période de la journée",
    "    df['day_period'] = pd.cut(",
    "        df['hour_of_day'],",
    "        bins=[0, 6, 12, 18, 24],",
    "        labels=['night', 'morning', 'afternoon', 'evening'],",
    "        right=False",
    "    ).astype(str)",
    "",
    "    # Délai depuis la transaction précédente",
    "    df_sorted = df.sort_values('Time')",
    "    df_sorted['time_since_last_tx'] = df_sorted['Time'].diff().fillna(0)",
    "    df['time_since_last_tx'] = df_sorted['time_since_last_tx']",
    "",
    "    # Indicateur de transaction nocturne",
    "    df['is_night'] = ((df['hour_of_day'] >= 0) & (df['hour_of_day'] < 6)).astype(int)",
    "",
    "    return df",
  ]),
  ...space(1),
  h3("4.3.2 Features statistiques sur le montant"),
  codeBlock([
    "# src/features/statistical.py",
    "",
    "def add_amount_features(df: pd.DataFrame, window: int = 100) -> pd.DataFrame:",
    '    """Crée des features statistiques sur le montant."""',
    "    df = df.copy()",
    "",
    "    # Log-transform (réduit l'effet des outliers)",
    "    df['amount_log'] = np.log1p(df['Amount'])",
    "",
    "    # Z-score glissant sur les 100 dernières transactions",
    "    rolling_mean = df['Amount'].rolling(window=window, min_periods=1).mean()",
    "    rolling_std  = df['Amount'].rolling(window=window, min_periods=1).std().fillna(1)",
    "    df['amount_zscore'] = (df['Amount'] - rolling_mean) / rolling_std",
    "",
    "    # Indicateur montant rond (fraudes souvent arrondies à l'euro)",
    "    df['is_round_amount'] = (df['Amount'] % 1 == 0).astype(int)",
    "",
    "    # Ratio par rapport à la médiane globale",
    "    median_amount = df['Amount'].median()",
    "    df['amount_vs_median'] = df['Amount'] / (median_amount + 1e-5)",
    "",
    "    return df",
  ]),
  ...space(1),
  h3("4.3.3 Features de vélocité"),
  codeBlock([
    "def add_velocity_features(df: pd.DataFrame) -> pd.DataFrame:",
    '    """Nombre et montant total de transactions dans des fenêtres temporelles."""',
    "    df = df.copy().sort_values('Time').reset_index(drop=True)",
    "",
    "    # Pour chaque fenêtre de temps (en secondes)",
    "    for window_sec, label in [(300, '5min'), (3600, '1h'), (86400, '24h')]:",
    "        counts = []",
    "        sums   = []",
    "",
    "        for i, row in df.iterrows():",
    "            mask = (",
    "                (df['Time'] >= row['Time'] - window_sec) &",
    "                (df['Time'] < row['Time'])",
    "            )",
    "            counts.append(mask.sum())",
    "            sums.append(df.loc[mask, 'Amount'].sum())",
    "",
    "        df[f'tx_count_{label}']  = counts",
    "        df[f'tx_amount_{label}'] = sums",
    "",
    "    return df",
  ]),
  ...space(1),
  h3("4.3.4 Pipeline sklearn complet"),
  codeBlock([
    "# src/features/pipeline.py",
    "",
    "from sklearn.pipeline import Pipeline",
    "from sklearn.preprocessing import StandardScaler, RobustScaler",
    "from sklearn.compose import ColumnTransformer",
    "",
    "def build_feature_pipeline(numeric_features: list, categorical_features: list = []):",
    '    """',
    "    Construit un pipeline sklearn pour le preprocessing.",
    "    RobustScaler est préféré à StandardScaler pour les données financières",
    "    car il est résistant aux outliers (utilise la médiane et l'IQR).",
    '    """',
    "    numeric_transformer = Pipeline(steps=[",
    "        ('scaler', RobustScaler())",
    "    ])",
    "",
    "    preprocessor = ColumnTransformer(",
    "        transformers=[",
    "            ('num', numeric_transformer, numeric_features),",
    "        ],",
    "        remainder='passthrough'",
    "    )",
    "",
    "    return preprocessor",
  ]),
  ...space(1),
  h2("4.4 Gestion du déséquilibre de classes"),
  infoBox("✅ RÈGLE ABSOLUE", "Ne JAMAIS appliquer SMOTE ou tout rééchantillonnage avant de séparer train/test. Cela provoque une fuite de données (data leakage) et gonfle artificiellement les métriques.", C.greenBg),
  ...space(1),
  p("Trois stratégies à comparer dans les expériences :"),
  ...space(1),
  new Table({
    width: { size: 9360, type: WidthType.DXA },
    columnWidths: [2800, 3280, 3280],
    rows: [
      new TableRow({ children: [
        cell([p([t("Méthode", { bold: true, color: C.white, size: 19 })])], { w: 2800, fill: C.tableHead }),
        cell([p([t("Avantages", { bold: true, color: C.white, size: 19 })])], { w: 3280, fill: C.tableHead }),
        cell([p([t("Inconvénients", { bold: true, color: C.white, size: 19 })])], { w: 3280, fill: C.tableHead }),
      ]}),
      ...[
        ["class_weight='balanced'", "Simple, rapide, sans modification des données", "Moins efficace sur déséquilibre extrême"],
        ["SMOTE (sur-échantillonnage)", "Crée de nouveaux exemples synthétiques réalistes", "Risque de bruit, coûteux en mémoire"],
        ["scale_pos_weight (XGBoost)", "Natif XGBoost, optimisé pour arbres de décision", "Spécifique à XGBoost/LightGBM"],
      ].map(([m, a, i_], i) => new TableRow({ children: [
        cell([p([t(m, { bold: true, size: 18, color: C.primary, font: "Courier New" })])],
          { w: 2800, fill: i % 2 === 0 ? C.grayBg : C.white }),
        cell([p([t(a, { size: 19, color: C.gray1 })])],
          { w: 3280, fill: i % 2 === 0 ? C.grayBg : C.white }),
        cell([p([t(i_, { size: 19, color: C.gray2 })])],
          { w: 3280, fill: i % 2 === 0 ? C.grayBg : C.white }),
      ]})),
    ],
  }),
  new Paragraph({ children: [new PageBreak()] }),
];

// ─── SECTION 5 : MODÉLISATION ────────────────────────────
const section5 = [
  h1("5. Pipeline de Modélisation"),
  h2("5.1 Métriques d'évaluation"),
  infoBox("🚨 CRITIQUE", "L'accuracy est une métrique TROMPEUSE sur ce dataset. Un modèle prédisant toujours 0 obtient 99.83% d'accuracy. Utiliser exclusivement PR-AUC, F1 sur classe 1, et le coût métier personnalisé.", C.redBg),
  ...space(1),
  new Table({
    width: { size: 9360, type: WidthType.DXA },
    columnWidths: [2800, 4760, 1800],
    rows: [
      new TableRow({ children: [
        cell([p([t("Métrique", { bold: true, color: C.white, size: 19 })])], { w: 2800, fill: C.tableHead }),
        cell([p([t("Définition & Utilité", { bold: true, color: C.white, size: 19 })])], { w: 4760, fill: C.tableHead }),
        cell([p([t("Cible", { bold: true, color: C.white, size: 19 })])], { w: 1800, fill: C.tableHead }),
      ]}),
      ...[
        ["PR-AUC", "Aire sous la courbe Précision-Rappel. Métrique principale pour données déséquilibrées.", "≥ 0.85"],
        ["F1-Score (classe 1)", "Moyenne harmonique précision/rappel sur les fraudes uniquement.", "≥ 0.80"],
        ["Recall (sensibilité)", "Taux de fraudes correctement détectées. Priorité métier : ne pas rater une fraude.", "≥ 0.85"],
        ["Coût métier total", "FN × 500€ + FP × 10€. Simule le coût réel opérationnel en banque.", "Minimiser"],
        ["Latence p95", "95ème percentile du temps de réponse de l'API. Contrainte de production.", "< 50 ms"],
      ].map(([m, d, c], i) => new TableRow({ children: [
        cell([p([t(m, { bold: true, size: 19, color: C.primary })])],
          { w: 2800, fill: i % 2 === 0 ? C.grayBg : C.white }),
        cell([p([t(d, { size: 19, color: C.gray1 })])],
          { w: 4760, fill: i % 2 === 0 ? C.grayBg : C.white }),
        cell([p([t(c, { size: 19, color: C.green, bold: true })])],
          { w: 1800, fill: i % 2 === 0 ? C.grayBg : C.white }),
      ]})),
    ],
  }),
  ...space(1),
  h2("5.2 Stratégie de validation"),
  p("Utiliser un StratifiedKFold temporel : les données sont triées par Time, et les folds respectent l'ordre chronologique pour éviter toute fuite temporelle (utiliser les transactions futures pour prédire les passées est une erreur classique)."),
  ...space(1),
  codeBlock([
    "# src/models/train.py",
    "",
    "from sklearn.model_selection import StratifiedKFold, cross_validate",
    "from sklearn.metrics import average_precision_score, f1_score",
    "import numpy as np",
    "",
    "def evaluate_model(model, X, y, n_splits: int = 5) -> dict:",
    '    """',
    "    Évalue un modèle avec validation croisée stratifiée.",
    "    shuffle=False pour respecter l'ordre temporel des données.",
    '    """',
    "    cv = StratifiedKFold(n_splits=n_splits, shuffle=False)",
    "",
    "    scores = cross_validate(",
    "        model, X, y,",
    "        cv=cv,",
    "        scoring={",
    "            'pr_auc': 'average_precision',",
    "            'f1': 'f1',",
    "            'recall': 'recall',",
    "        },",
    "        return_train_score=True,",
    "        n_jobs=-1",
    "    )",
    "",
    "    return {",
    "        'pr_auc_mean':  scores['test_pr_auc'].mean(),",
    "        'pr_auc_std':   scores['test_pr_auc'].std(),",
    "        'f1_mean':      scores['test_f1'].mean(),",
    "        'recall_mean':  scores['test_recall'].mean(),",
    "        'overfit_gap':  (scores['train_pr_auc'] - scores['test_pr_auc']).mean(),",
    "    }",
  ]),
  ...space(1),
  h2("5.3 Comparaison des modèles"),
  p("Ordre d'expérimentation recommandé — du plus simple au plus complexe. Chaque modèle doit être trackée dans MLflow (voir Section 8)."),
  ...space(1),
  new Table({
    width: { size: 9360, type: WidthType.DXA },
    columnWidths: [2200, 1800, 1800, 3560],
    rows: [
      new TableRow({ children: [
        cell([p([t("Modèle", { bold: true, color: C.white, size: 19 })])], { w: 2200, fill: C.tableHead }),
        cell([p([t("PR-AUC attendu", { bold: true, color: C.white, size: 19 })])], { w: 1800, fill: C.tableHead }),
        cell([p([t("Rôle", { bold: true, color: C.white, size: 19 })])], { w: 1800, fill: C.tableHead }),
        cell([p([t("Paramètre clé déséquilibre", { bold: true, color: C.white, size: 19 })])], { w: 3560, fill: C.tableHead }),
      ]}),
      ...[
        ["Régression Logistique", "0.65–0.70", "Baseline", "class_weight='balanced'"],
        ["Random Forest", "0.75–0.80", "Référence", "class_weight='balanced'"],
        ["XGBoost", "0.83–0.87", "Candidat principal", "scale_pos_weight=578"],
        ["LightGBM", "0.84–0.88", "Candidat principal", "is_unbalance=True"],
        ["Isolation Forest", "0.60–0.70", "Non-supervisé (comparaison)", "contamination=0.002"],
        ["Ensemble (Voting)", "0.86–0.90", "Modèle final", "Combinaison XGB + LGBM"],
      ].map(([m, pr, role, param], i) => new TableRow({ children: [
        cell([p([t(m, { bold: true, size: 18, color: C.primary })])],
          { w: 2200, fill: i % 2 === 0 ? C.grayBg : C.white }),
        cell([p([t(pr, { size: 19, color: C.green })])],
          { w: 1800, fill: i % 2 === 0 ? C.grayBg : C.white }),
        cell([p([t(role, { size: 19, color: C.gray2 })])],
          { w: 1800, fill: i % 2 === 0 ? C.grayBg : C.white }),
        cell([p([t(param, { size: 17, font: "Courier New", color: C.blue })])],
          { w: 3560, fill: i % 2 === 0 ? C.grayBg : C.white }),
      ]})),
    ],
  }),
  ...space(1),
  h2("5.4 Optimisation des hyperparamètres avec Optuna"),
  p("Optuna utilise la méthode bayésienne (Tree-structured Parzen Estimator) pour explorer l'espace des hyperparamètres de façon intelligente. Il est 10x plus efficace qu'un GridSearch et 3x plus qu'un RandomSearch."),
  ...space(1),
  codeBlock([
    "# src/models/train.py",
    "",
    "import optuna",
    "from xgboost import XGBClassifier",
    "from sklearn.model_selection import cross_val_score",
    "",
    "def optimize_xgboost(X_train, y_train, n_trials: int = 100) -> dict:",
    '    """Optimise les hyperparamètres XGBoost avec Optuna."""',
    "",
    "    # Ratio négatifs/positifs pour scale_pos_weight",
    "    pos_weight = (y_train == 0).sum() / (y_train == 1).sum()",
    "",
    "    def objective(trial):",
    "        params = {",
    "            'n_estimators':     trial.suggest_int('n_estimators', 100, 1000),",
    "            'max_depth':        trial.suggest_int('max_depth', 3, 10),",
    "            'learning_rate':    trial.suggest_float('learning_rate', 0.01, 0.3, log=True),",
    "            'subsample':        trial.suggest_float('subsample', 0.6, 1.0),",
    "            'colsample_bytree': trial.suggest_float('colsample_bytree', 0.6, 1.0),",
    "            'min_child_weight': trial.suggest_int('min_child_weight', 1, 20),",
    "            'reg_alpha':        trial.suggest_float('reg_alpha', 1e-8, 1.0, log=True),",
    "            'reg_lambda':       trial.suggest_float('reg_lambda', 1e-8, 1.0, log=True),",
    "            'scale_pos_weight': pos_weight,",
    "            'eval_metric':      'aucpr',   # Optimise PR-AUC, pas l'accuracy",
    "            'random_state':     42,",
    "        }",
    "        model = XGBClassifier(**params)",
    "        score = cross_val_score(",
    "            model, X_train, y_train,",
    "            cv=3, scoring='average_precision', n_jobs=-1",
    "        ).mean()",
    "        return score",
    "",
    "    study = optuna.create_study(direction='maximize')",
    "    study.optimize(objective, n_trials=n_trials, show_progress_bar=True)",
    "",
    "    return study.best_params",
  ]),
  new Paragraph({ children: [new PageBreak()] }),
];

// ─── SECTION 6 : EXPLICABILITÉ ───────────────────────────
const section6 = [
  h1("6. Explicabilité & Visualisation"),
  h2("6.1 Pourquoi l'explicabilité est critique en finance"),
  p("Le RGPD (Article 22) et la directive DSP2 imposent aux institutions financières de pouvoir expliquer toute décision automatisée ayant un impact sur un client (refus de transaction, blocage de compte). Un modèle \"boîte noire\" non explicable ne peut pas être déployé légalement en production bancaire."),
  ...space(1),
  h2("6.2 Implémentation SHAP"),
  h3("6.2.1 SHAP global — importance des features"),
  codeBlock([
    "# src/explainability/shap_utils.py",
    "",
    "import shap",
    "import matplotlib.pyplot as plt",
    "import pandas as pd",
    "import numpy as np",
    "",
    "def compute_shap_values(model, X: pd.DataFrame) -> tuple:",
    '    """',
    "    Calcule les valeurs SHAP pour un modèle arbre.",
    "    Retourne l'explainer et les valeurs SHAP.",
    '    """',
    "    explainer = shap.TreeExplainer(model)",
    "    shap_values = explainer.shap_values(X)",
    "    return explainer, shap_values",
    "",
    "def plot_shap_summary(shap_values, X: pd.DataFrame, save_path: str = None):",
    '    """Summary plot : importance globale de chaque feature."""',
    "    plt.figure(figsize=(10, 8))",
    "    shap.summary_plot(",
    "        shap_values, X,",
    "        plot_type='bar',     # Importance moyenne absolue",
    "        show=False",
    "    )",
    "    if save_path:",
    "        plt.savefig(save_path, dpi=150, bbox_inches='tight')",
    "    plt.close()",
  ]),
  ...space(1),
  h3("6.2.2 SHAP local — explication d'une transaction"),
  codeBlock([
    "def explain_single_transaction(",
    "    explainer,",
    "    shap_values: np.ndarray,",
    "    X: pd.DataFrame,",
    "    transaction_idx: int",
    ") -> dict:",
    '    """',
    "    Explique la décision sur une transaction individuelle.",
    "    Retourne le top-3 des features les plus influentes.",
    '    """',
    "    tx_shap = shap_values[transaction_idx]",
    "    feature_names = X.columns.tolist()",
    "",
    "    # Trier par valeur absolue décroissante",
    "    sorted_idx = np.argsort(np.abs(tx_shap))[::-1]",
    "",
    "    top_features = []",
    "    for i in sorted_idx[:3]:",
    "        top_features.append({",
    "            'feature':    feature_names[i],",
    "            'value':      float(X.iloc[transaction_idx, i]),",
    "            'shap_value': float(tx_shap[i]),",
    "            'impact':     'risk_increase' if tx_shap[i] > 0 else 'risk_decrease'",
    "        })",
    "",
    "    return {",
    "        'top_3_features': top_features,",
    "        'base_value': float(explainer.expected_value),",
    "    }",
  ]),
  new Paragraph({ children: [new PageBreak()] }),
];

// ─── SECTION 7 : API ─────────────────────────────────────
const section7 = [
  h1("7. API & Déploiement"),
  h2("7.1 Architecture de l'API"),
  p("L'API expose trois endpoints principaux. Elle doit répondre en moins de 50ms (p95) et renvoyer systématiquement les raisons de la décision (explicabilité)."),
  ...space(1),
  new Table({
    width: { size: 9360, type: WidthType.DXA },
    columnWidths: [1400, 1400, 2000, 4560],
    rows: [
      new TableRow({ children: [
        cell([p([t("Méthode", { bold: true, color: C.white, size: 19 })])], { w: 1400, fill: C.tableHead }),
        cell([p([t("Route", { bold: true, color: C.white, size: 19 })])], { w: 1400, fill: C.tableHead }),
        cell([p([t("Description", { bold: true, color: C.white, size: 19 })])], { w: 2000, fill: C.tableHead }),
        cell([p([t("Réponse attendue", { bold: true, color: C.white, size: 19 })])], { w: 4560, fill: C.tableHead }),
      ]}),
      new TableRow({ children: [
        cell([p([t("GET", { bold: true, size: 18, color: C.green })])], { w: 1400, fill: C.grayBg }),
        cell([p([t("/health", { size: 17, font: "Courier New", color: C.primary })])], { w: 1400, fill: C.grayBg }),
        cell([p([t("Statut de l'API", { size: 19, color: C.gray1 })])], { w: 2000, fill: C.grayBg }),
        cell([p([t("{ status: 'ok', model_version, uptime_s }", { size: 16, font: "Courier New", color: C.gray2 })])], { w: 4560, fill: C.grayBg }),
      ]}),
      new TableRow({ children: [
        cell([p([t("POST", { bold: true, size: 18, color: C.blue })])], { w: 1400, fill: C.white }),
        cell([p([t("/predict", { size: 17, font: "Courier New", color: C.primary })])], { w: 1400, fill: C.white }),
        cell([p([t("Prédiction fraude", { size: 19, color: C.gray1 })])], { w: 2000, fill: C.white }),
        cell([p([t("{ fraud_score, decision, top_risk_factors, latency_ms }", { size: 16, font: "Courier New", color: C.gray2 })])], { w: 4560, fill: C.white }),
      ]}),
      new TableRow({ children: [
        cell([p([t("GET", { bold: true, size: 18, color: C.green })])], { w: 1400, fill: C.grayBg }),
        cell([p([t("/metrics", { size: 17, font: "Courier New", color: C.primary })])], { w: 1400, fill: C.grayBg }),
        cell([p([t("Métriques Prometheus", { size: 19, color: C.gray1 })])], { w: 2000, fill: C.grayBg }),
        cell([p([t("Format texte pour monitoring Grafana", { size: 16, color: C.gray2 })])], { w: 4560, fill: C.grayBg }),
      ]}),
    ],
  }),
  ...space(1),
  h2("7.2 Implémentation FastAPI"),
  h3("7.2.1 Schémas Pydantic (validation des entrées)"),
  codeBlock([
    "# api/schemas.py",
    "",
    "from pydantic import BaseModel, Field, validator",
    "from typing import Literal",
    "",
    "class TransactionInput(BaseModel):",
    '    """Schéma de validation pour une transaction entrante."""',
    "",
    "    time:   float = Field(..., description='Secondes depuis 1ère tx (>=0)', ge=0)",
    "    amount: float = Field(..., description='Montant de la transaction (>=0)', ge=0)",
    "    v1:     float = Field(..., description='Composante PCA V1')",
    "    # ... v2 à v28 de la même façon",
    "    v28:    float = Field(..., description='Composante PCA V28')",
    "",
    "    class Config:",
    "        json_schema_extra = {",
    "            'example': {",
    "                'time': 406, 'amount': 149.62,",
    "                'v1': -1.359807, 'v2': -0.072781,",
    "                # ...",
    "                'v28': -0.021053",
    "            }",
    "        }",
    "",
    "class TopFeature(BaseModel):",
    "    feature:    str",
    "    value:      float",
    "    shap_value: float",
    "    impact:     Literal['risk_increase', 'risk_decrease']",
    "",
    "class PredictionOutput(BaseModel):",
    "    fraud_score:      float = Field(..., ge=0, le=1)",
    "    decision:         Literal['BLOCK', 'REVIEW', 'ALLOW']",
    "    top_risk_factors: list[TopFeature]",
    "    latency_ms:       float",
    "    model_version:    str",
  ]),
  ...space(1),
  h3("7.2.2 Endpoint de prédiction"),
  codeBlock([
    "# api/main.py",
    "",
    "from fastapi import FastAPI, HTTPException",
    "from contextlib import asynccontextmanager",
    "import time, joblib, os",
    "from api.schemas import TransactionInput, PredictionOutput",
    "from src.features.pipeline import transform_single_transaction",
    "from src.explainability.shap_utils import explain_single_transaction",
    "",
    "# Chargement du modèle au démarrage (une seule fois)",
    "model = None",
    "explainer = None",
    "",
    "@asynccontextmanager",
    "async def lifespan(app: FastAPI):",
    "    global model, explainer",
    "    model_path = os.getenv('MODEL_PATH', 'models/fraud_detector_v1.pkl')",
    "    model = joblib.load(model_path)",
    "    import shap",
    "    explainer = shap.TreeExplainer(model)",
    "    yield  # L'application est active",
    "",
    "app = FastAPI(title='Fraud Detection API', version='1.0.0', lifespan=lifespan)",
    "",
    "@app.post('/predict', response_model=PredictionOutput)",
    "async def predict_fraud(transaction: TransactionInput):",
    "    start_time = time.perf_counter()",
    "",
    "    # 1. Transformer en features",
    "    X = transform_single_transaction(transaction.model_dump())",
    "",
    "    # 2. Prédiction",
    "    fraud_score = float(model.predict_proba(X)[0, 1])",
    "",
    "    # 3. Décision selon seuils",
    "    block_threshold  = float(os.getenv('FRAUD_THRESHOLD', 0.8))",
    "    review_threshold = float(os.getenv('REVIEW_THRESHOLD', 0.4))",
    "",
    "    if fraud_score >= block_threshold:",
    "        decision = 'BLOCK'",
    "    elif fraud_score >= review_threshold:",
    "        decision = 'REVIEW'",
    "    else:",
    "        decision = 'ALLOW'",
    "",
    "    # 4. Explicabilité SHAP",
    "    shap_values = explainer.shap_values(X)",
    "    explanation = explain_single_transaction(explainer, shap_values, X, 0)",
    "",
    "    latency_ms = (time.perf_counter() - start_time) * 1000",
    "",
    "    return PredictionOutput(",
    "        fraud_score=round(fraud_score, 4),",
    "        decision=decision,",
    "        top_risk_factors=explanation['top_3_features'],",
    "        latency_ms=round(latency_ms, 2),",
    "        model_version='1.0.0'",
    "    )",
  ]),
  ...space(1),
  h2("7.3 Dockerfile"),
  codeBlock([
    "# Multi-stage build pour réduire la taille de l'image finale",
    "FROM python:3.11-slim AS builder",
    "",
    "WORKDIR /app",
    "COPY requirements.txt .",
    "RUN pip install --no-cache-dir -r requirements.txt",
    "",
    "# ── Image finale ──────────────────────────────────",
    "FROM python:3.11-slim",
    "",
    "WORKDIR /app",
    "",
    "# Copier uniquement les packages installés depuis le builder",
    "COPY --from=builder /usr/local/lib/python3.11/site-packages \\",
    "     /usr/local/lib/python3.11/site-packages",
    "COPY --from=builder /usr/local/bin /usr/local/bin",
    "",
    "# Copier le code source",
    "COPY src/ ./src/",
    "COPY api/ ./api/",
    "COPY models/ ./models/",
    "COPY .env.example ./.env",
    "",
    "EXPOSE 8000",
    "",
    "HEALTHCHECK --interval=30s --timeout=10s --start-period=5s \\",
    "  CMD curl -f http://localhost:8000/health || exit 1",
    "",
    "CMD [\"uvicorn\", \"api.main:app\", \"--host\", \"0.0.0.0\", \"--port\", \"8000\", \"--workers\", \"2\"]",
  ]),
  new Paragraph({ children: [new PageBreak()] }),
];

// ─── SECTION 8 : MLFLOW ──────────────────────────────────
const section8 = [
  h1("8. MLflow & Suivi des expériences"),
  h2("8.1 Pourquoi tracker toutes les expériences"),
  p("MLflow permet de reproduire n'importe quelle expérience passée, de comparer les modèles visuellement, et de promouvoir le meilleur modèle en production de façon traçable. C'est la différence entre un \"projet Kaggle\" et un pipeline ML professionnel."),
  ...space(1),
  h2("8.2 Intégration MLflow dans le pipeline d'entraînement"),
  codeBlock([
    "# src/models/train.py",
    "",
    "import mlflow",
    "import mlflow.sklearn",
    "from datetime import datetime",
    "",
    "def train_and_log(model, X_train, y_train, X_test, y_test,",
    "                   model_name: str, params: dict) -> str:",
    '    """',
    "    Entraîne un modèle et log tous les artefacts dans MLflow.",
    "    Retourne le run_id pour référence future.",
    '    """',
    "    mlflow.set_experiment(os.getenv('MLFLOW_EXPERIMENT_NAME', 'fraud_detection'))",
    "",
    "    run_name = f'{model_name}_{datetime.now().strftime(\"%Y%m%d_%H%M\")}'",
    "",
    "    with mlflow.start_run(run_name=run_name) as run:",
    "        # 1. Log des paramètres",
    "        mlflow.log_params(params)",
    "",
    "        # 2. Entraînement",
    "        model.fit(X_train, y_train)",
    "",
    "        # 3. Calcul des métriques",
    "        y_proba = model.predict_proba(X_test)[:, 1]",
    "        y_pred  = (y_proba >= 0.5).astype(int)",
    "",
    "        metrics = {",
    "            'pr_auc':        average_precision_score(y_test, y_proba),",
    "            'f1_fraud':      f1_score(y_test, y_pred),",
    "            'recall_fraud':  recall_score(y_test, y_pred),",
    "            'precision_fraud': precision_score(y_test, y_pred),",
    "            'business_cost': compute_business_cost(y_test, y_pred),",
    "        }",
    "        mlflow.log_metrics(metrics)",
    "",
    "        # 4. Log du modèle",
    "        mlflow.sklearn.log_model(",
    "            model, 'model',",
    "            registered_model_name='fraud_detector'",
    "        )",
    "",
    "        # 5. Log des artefacts visuels",
    "        mlflow.log_artifact('reports/shap_summary.png')",
    "        mlflow.log_artifact('reports/pr_curve.png')",
    "",
    "        print(f'Run ID: {run.info.run_id}')",
    "        print(f'PR-AUC: {metrics[\"pr_auc\"]:.4f}')",
    "",
    "        return run.info.run_id",
  ]),
  ...space(1),
  h2("8.3 Promotion du modèle en production"),
  codeBlock([
    "# Promouvoir le meilleur run en production via MLflow Model Registry",
    "",
    "import mlflow",
    "from mlflow.tracking import MlflowClient",
    "",
    "client = MlflowClient()",
    "",
    "# Récupérer le run avec le meilleur PR-AUC",
    "experiment = client.get_experiment_by_name('fraud_detection')",
    "best_run = client.search_runs(",
    "    experiment_ids=[experiment.experiment_id],",
    "    order_by=['metrics.pr_auc DESC'],",
    "    max_results=1",
    ")[0]",
    "",
    "# Créer une nouvelle version dans le Model Registry",
    "model_version = mlflow.register_model(",
    "    f'runs:/{best_run.info.run_id}/model',",
    "    'fraud_detector'",
    ")",
    "",
    "# Transition vers Production",
    "client.transition_model_version_stage(",
    "    name='fraud_detector',",
    "    version=model_version.version,",
    "    stage='Production',",
    "    archive_existing_versions=True  # Archive l'ancien modèle de production",
    ")",
    "",
    "print(f'Modèle v{model_version.version} promu en Production')",
    "print(f'PR-AUC: {best_run.data.metrics[\"pr_auc\"]:.4f}')",
  ]),
  new Paragraph({ children: [new PageBreak()] }),
];

// ─── SECTION 9 : TESTS ───────────────────────────────────
const section9 = [
  h1("9. Tests & Qualité du code"),
  h2("9.1 Stratégie de tests"),
  p("Trois niveaux de tests sont requis, dans l'ordre d'implémentation :"),
  bullet("Tests unitaires : chaque fonction individuellement (features, métriques, preprocessing)"),
  bullet("Tests d'intégration : pipeline complet data → modèle → API"),
  bullet("Tests de non-régression : le nouveau modèle doit faire mieux que l'ancien sur les métriques critiques"),
  ...space(1),
  h2("9.2 Exemples de tests unitaires"),
  codeBlock([
    "# tests/test_features.py",
    "",
    "import pytest",
    "import pandas as pd",
    "import numpy as np",
    "from src.features.statistical import add_amount_features",
    "from src.features.temporal import add_temporal_features",
    "",
    "class TestAmountFeatures:",
    "",
    "    def test_log_transform_never_negative(self, sample_df):",
    '        """Le log1p d\'un montant positif doit toujours être >= 0."""',
    "        result = add_amount_features(sample_df)",
    "        assert (result['amount_log'] >= 0).all()",
    "",
    "    def test_round_amount_detection(self):",
    '        """Les montants ronds doivent être correctement identifiés."""',
    "        df = pd.DataFrame({'Amount': [100.0, 99.99, 50.0, 0.01]})",
    "        result = add_amount_features(df)",
    "        expected = [1, 0, 1, 0]",
    "        assert list(result['is_round_amount']) == expected",
    "",
    "    def test_no_data_leakage(self, sample_df):",
    '        """Le z-score glissant ne doit pas utiliser des données futures."""',
    "        result = add_amount_features(sample_df, window=10)",
    "        # La première valeur doit utiliser uniquement elle-même",
    "        assert not np.isnan(result['amount_zscore'].iloc[0])",
    "",
    "",
    "# tests/test_api.py",
    "",
    "from fastapi.testclient import TestClient",
    "from api.main import app",
    "",
    "client = TestClient(app)",
    "",
    "def test_health_endpoint():",
    "    response = client.get('/health')",
    "    assert response.status_code == 200",
    "    assert response.json()['status'] == 'ok'",
    "",
    "def test_predict_valid_transaction():",
    "    tx = {",
    "        'time': 406.0, 'amount': 149.62,",
    "        **{f'v{i}': 0.0 for i in range(1, 29)}",
    "    }",
    "    response = client.post('/predict', json=tx)",
    "    assert response.status_code == 200",
    "    data = response.json()",
    "    assert 0 <= data['fraud_score'] <= 1",
    "    assert data['decision'] in ['BLOCK', 'REVIEW', 'ALLOW']",
    "    assert len(data['top_risk_factors']) == 3",
    "    assert data['latency_ms'] < 500  # tolérance large pour les tests",
  ]),
  ...space(1),
  h2("9.3 Pipeline CI/CD GitHub Actions"),
  codeBlock([
    "# .github/workflows/ci.yml",
    "",
    "name: CI Pipeline",
    "",
    "on:",
    "  push:",
    "    branches: [main, develop]",
    "  pull_request:",
    "    branches: [main]",
    "",
    "jobs:",
    "  test:",
    "    runs-on: ubuntu-latest",
    "    steps:",
    "      - uses: actions/checkout@v4",
    "",
    "      - name: Setup Python",
    "        uses: actions/setup-python@v5",
    "        with:",
    "          python-version: '3.11'",
    "",
    "      - name: Install dependencies",
    "        run: |",
    "          pip install -r requirements.txt",
    "          pip install -r requirements-dev.txt",
    "",
    "      - name: Run linter (black + flake8)",
    "        run: |",
    "          black --check src/ api/ tests/",
    "          flake8 src/ api/ tests/ --max-line-length=100",
    "",
    "      - name: Run tests with coverage",
    "        run: |",
    "          pytest tests/ -v --cov=src --cov-report=xml --cov-fail-under=80",
    "",
    "      - name: Upload coverage report",
    "        uses: codecov/codecov-action@v4",
  ]),
  new Paragraph({ children: [new PageBreak()] }),
];

// ─── SECTION 10 : LIVRABLES ──────────────────────────────
const section10 = [
  h1("10. Livrables & Critères de succès"),
  h2("10.1 Livrables obligatoires"),
  new Table({
    width: { size: 9360, type: WidthType.DXA },
    columnWidths: [2800, 4160, 2400],
    rows: [
      new TableRow({ children: [
        cell([p([t("Livrable", { bold: true, color: C.white, size: 19 })])], { w: 2800, fill: C.tableHead }),
        cell([p([t("Description", { bold: true, color: C.white, size: 19 })])], { w: 4160, fill: C.tableHead }),
        cell([p([t("Critère d'acceptation", { bold: true, color: C.white, size: 19 })])], { w: 2400, fill: C.tableHead }),
      ]}),
      ...[
        ["Code GitHub", "Dépôt public, README avec GIF de démo, badges CI", "README lisible < 5 min"],
        ["5 Notebooks", "EDA, Features, Modélisation, SHAP, Monitoring", "Reproductibles en 1 commande"],
        ["API déployée", "FastAPI sur Railway/Render, URL publique", "Accessible 24/7, /health = 200"],
        ["Dashboard Streamlit", "Interface de démo avec saisie de transaction", "Démo live fonctionnelle"],
        ["MLflow Registry", "≥ 20 expériences trackées, modèle en Production", "Comparaison visible en UI"],
        ["Rapport PDF", "Résultats, métriques, biais, recommandations", "10 pages, style professionnel"],
      ].map(([l, d, c], i) => new TableRow({ children: [
        cell([p([t(l, { bold: true, size: 19, color: C.primary })])],
          { w: 2800, fill: i % 2 === 0 ? C.grayBg : C.white }),
        cell([p([t(d, { size: 19, color: C.gray1 })])],
          { w: 4160, fill: i % 2 === 0 ? C.grayBg : C.white }),
        cell([p([t(c, { size: 19, color: C.green })])],
          { w: 2400, fill: i % 2 === 0 ? C.grayBg : C.white }),
      ]})),
    ],
  }),
  ...space(1),
  h2("10.2 Métriques cibles du modèle"),
  new Table({
    width: { size: 9360, type: WidthType.DXA },
    columnWidths: [2800, 1800, 2000, 2760],
    rows: [
      new TableRow({ children: [
        cell([p([t("Métrique", { bold: true, color: C.white, size: 19 })])], { w: 2800, fill: C.tableHead }),
        cell([p([t("Minimum", { bold: true, color: C.white, size: 19 })])], { w: 1800, fill: C.tableHead }),
        cell([p([t("Cible", { bold: true, color: C.white, size: 19 })])], { w: 2000, fill: C.tableHead }),
        cell([p([t("Référence (papier ULB)", { bold: true, color: C.white, size: 19 })])], { w: 2760, fill: C.tableHead }),
      ]}),
      ...[
        ["PR-AUC (test set)", "0.82", "≥ 0.87", "0.83 (Random Forest)"],
        ["F1-Score (fraude)", "0.75", "≥ 0.80", "0.77 (Random Forest)"],
        ["Recall (fraude)", "0.80", "≥ 0.85", "0.82"],
        ["Latence API p95", "< 100ms", "< 50ms", "N/A"],
        ["Couverture de tests", "70%", "≥ 80%", "N/A"],
      ].map(([m, mi, ta, ref], i) => new TableRow({ children: [
        cell([p([t(m, { bold: true, size: 19, color: C.primary })])],
          { w: 2800, fill: i % 2 === 0 ? C.grayBg : C.white }),
        cell([p([t(mi, { size: 19, color: C.red })])],
          { w: 1800, fill: i % 2 === 0 ? C.grayBg : C.white }),
        cell([p([t(ta, { size: 19, color: C.green, bold: true })])],
          { w: 2000, fill: i % 2 === 0 ? C.grayBg : C.white }),
        cell([p([t(ref, { size: 19, color: C.gray2 })])],
          { w: 2760, fill: i % 2 === 0 ? C.grayBg : C.white }),
      ]})),
    ],
  }),
  ...space(1),
  h2("10.3 Checklist de démarrage (Semaine 1)"),
  numbered("Créer le dépôt GitHub avec la structure de dossiers complète"),
  numbered("Télécharger le dataset Credit Card Fraud depuis Kaggle et le placer dans data/raw/"),
  numbered("Créer et activer l'environnement virtuel, installer les dépendances"),
  numbered("Configurer le fichier .env à partir du .env.example"),
  numbered("Créer le notebook 01_eda.ipynb et commencer l'analyse exploratoire"),
  numbered("Faire un premier commit avec la structure vide et le README initial"),
  ...space(1),
  infoBox("🎯 OBJECTIF", "À la fin du projet, tout le monde doit pouvoir cloner ton dépôt, exécuter 'docker compose up' et avoir l'API + le dashboard fonctionnels en moins de 5 minutes. C'est le vrai test de qualité d'un projet production.", C.greenBg),
  ...space(1),
  divider(),
  ...space(1),
  new Paragraph({
    alignment: AlignmentType.CENTER,
    spacing: { before: 80, after: 40 },
    children: [new TextRun({ text: "Document de spécifications v1.0.0 — Projet Détection de Fraude Bancaire", font: "Arial", size: 18, italic: true, color: C.gray3 })],
  }),
  new Paragraph({
    alignment: AlignmentType.CENTER,
    spacing: { before: 0, after: 0 },
    children: [new TextRun({ text: "Généré pour un étudiant en Data Science & IA — 2025", font: "Arial", size: 16, color: C.gray3 })],
  }),
];

// ─── DOCUMENT FINAL ───────────────────────────────────────
const doc = new Document({
  numbering: {
    config: [
      { reference: "bullets",
        levels: [{ level: 0, format: LevelFormat.BULLET, text: "•", alignment: AlignmentType.LEFT,
          style: { paragraph: { indent: { left: 720, hanging: 360 } } } },
          { level: 1, format: LevelFormat.BULLET, text: "◦", alignment: AlignmentType.LEFT,
          style: { paragraph: { indent: { left: 1080, hanging: 360 } } } }]
      },
      { reference: "numbers",
        levels: [{ level: 0, format: LevelFormat.DECIMAL, text: "%1.", alignment: AlignmentType.LEFT,
          style: { paragraph: { indent: { left: 720, hanging: 360 } } } }]
      },
    ]
  },
  styles: {
    default: { document: { run: { font: "Arial", size: 20 } } },
    paragraphStyles: [
      { id: "Heading1", name: "Heading 1", basedOn: "Normal", next: "Normal", quickFormat: true,
        run: { size: 36, bold: true, font: "Arial", color: C.primary },
        paragraph: { spacing: { before: 320, after: 160 }, outlineLevel: 0 } },
      { id: "Heading2", name: "Heading 2", basedOn: "Normal", next: "Normal", quickFormat: true,
        run: { size: 28, bold: true, font: "Arial", color: C.primary },
        paragraph: { spacing: { before: 240, after: 120 }, outlineLevel: 1 } },
      { id: "Heading3", name: "Heading 3", basedOn: "Normal", next: "Normal", quickFormat: true,
        run: { size: 24, bold: true, font: "Arial", color: C.blue },
        paragraph: { spacing: { before: 160, after: 80 }, outlineLevel: 2 } },
    ]
  },
  sections: [{
    properties: {
      page: {
        size: { width: 11906, height: 16838 },
        margin: { top: 1134, right: 1134, bottom: 1134, left: 1134 }
      }
    },
    headers: {
      default: new Header({
        children: [
          new Paragraph({
            spacing: { before: 0, after: 160 },
            border: { bottom: { style: BorderStyle.SINGLE, size: 4, color: C.accent } },
            children: [
              new TextRun({ text: "Spécifications Techniques — Détection de Fraude Bancaire", font: "Arial", size: 16, color: C.gray2 }),
              new TextRun({ text: "    |    v1.0.0", font: "Arial", size: 16, color: C.gray3 }),
            ],
          })
        ]
      })
    },
    footers: {
      default: new Footer({
        children: [
          new Paragraph({
            spacing: { before: 100, after: 0 },
            border: { top: { style: BorderStyle.SINGLE, size: 4, color: C.border } },
            tabStops: [{ type: TabStopType.RIGHT, position: 9026 }],
            children: [
              new TextRun({ text: "Projet ML — Data Science & IA", font: "Arial", size: 16, color: C.gray3 }),
              new TextRun({ text: "\t", font: "Arial", size: 16 }),
              new TextRun({ text: "Page ", font: "Arial", size: 16, color: C.gray2 }),
              new TextRun({ font: "Arial", size: 16, color: C.gray2, children: [PageNumber.CURRENT] }),
            ],
          })
        ]
      })
    },
    children: [
      ...coverPage,
      ...tocPage,
      ...section1,
      ...section2,
      ...section3,
      ...section4,
      ...section5,
      ...section6,
      ...section7,
      ...section8,
      ...section9,
      ...section10,
    ]
  }]
});

Packer.toBuffer(doc).then(buffer => {
  fs.writeFileSync('/home/claude/specifications_fraude_bancaire.docx', buffer);
  console.log('Done');
});
